const propertyOrder = [
  {
    groupName: 'Positioning',
    emptyLineBefore: 'never',
    properties: [
      'position',
      'inset',
      'inset-block',
      'inset-inline',
      'top',
      'right',
      'bottom',
      'left',
      'z-index',
      'isolation',
    ],
  },
  {
    groupName: 'Display and layout',
    emptyLineBefore: 'never',
    properties: [
      'display',
      'visibility',
      'overflow',
      'overflow-x',
      'overflow-y',
      'clip',
      'float',
      'clear',
    ],
  },
  {
    groupName: 'Flex and grid',
    emptyLineBefore: 'never',
    properties: [
      'flex',
      'flex-direction',
      'flex-wrap',
      'flex-flow',
      'flex-grow',
      'flex-shrink',
      'flex-basis',
      'align-items',
      'align-content',
      'align-self',
      'justify-content',
      'justify-items',
      'justify-self',
      'place-content',
      'place-items',
      'place-self',
      'order',
      'grid',
      'grid-template',
      'grid-template-columns',
      'grid-template-rows',
      'grid-template-areas',
      'grid-auto-columns',
      'grid-auto-rows',
      'grid-auto-flow',
      'grid-column',
      'grid-column-start',
      'grid-column-end',
      'grid-row',
      'grid-row-start',
      'grid-row-end',
      'grid-area',
      'gap',
      'row-gap',
      'column-gap',
    ],
  },
  {
    groupName: 'Box model',
    emptyLineBefore: 'never',
    properties: [
      'box-sizing',
      'margin',
      'margin-block',
      'margin-inline',
      'margin-top',
      'margin-right',
      'margin-bottom',
      'margin-left',
      'padding',
      'padding-block',
      'padding-inline',
      'padding-top',
      'padding-right',
      'padding-bottom',
      'padding-left',
    ],
  },
  {
    groupName: 'Sizing',
    emptyLineBefore: 'never',
    properties: [
      'width',
      'min-width',
      'max-width',
      'height',
      'min-height',
      'max-height',
      'aspect-ratio',
    ],
  },
  {
    groupName: 'Typography',
    emptyLineBefore: 'never',
    properties: [
      'font',
      'font-family',
      'font-size',
      'font-style',
      'font-weight',
      'font-variant',
      'font-variant-numeric',
      'line-height',
      'letter-spacing',
      'text-align',
      'text-decoration',
      'text-transform',
      'text-overflow',
      'text-underline-offset',
      'white-space',
      'word-break',
      'overflow-wrap',
      'color',
    ],
  },
  {
    groupName: 'Visuals',
    emptyLineBefore: 'never',
    properties: [
      'background',
      'background-color',
      'background-image',
      'background-position',
      'background-size',
      'background-repeat',
      'border',
      'border-top',
      'border-right',
      'border-bottom',
      'border-left',
      'border-color',
      'border-width',
      'border-style',
      'border-radius',
      'box-shadow',
      'opacity',
      'filter',
      'backdrop-filter',
      'outline',
    ],
  },
  {
    groupName: 'Interaction',
    emptyLineBefore: 'never',
    properties: [
      'pointer-events',
      'cursor',
      'resize',
      'user-select',
      'touch-action',
      'appearance',
    ],
  },
  {
    groupName: 'Motion and transforms',
    emptyLineBefore: 'never',
    properties: [
      'transform',
      'transform-origin',
      'transition',
      'transition-property',
      'transition-duration',
      'transition-timing-function',
      'transition-delay',
      'animation',
      'animation-name',
      'animation-duration',
      'animation-timing-function',
      'animation-delay',
      'animation-iteration-count',
      'animation-direction',
      'animation-fill-mode',
      'will-change',
    ],
  },
];

const stylelintConfig = {
  extends: ['stylelint-config-standard-scss'],
  plugins: ['stylelint-order'],
  customSyntax: 'postcss-scss',
  ignoreFiles: ['.next/**', 'node_modules/**', 'out/**', 'build/**'],
  rules: {
    'at-rule-empty-line-before': null,
    'alpha-value-notation': null,
    'color-function-alias-notation': null,
    'color-function-notation': null,
    'color-hex-length': null,
    'comment-empty-line-before': null,
    'custom-property-empty-line-before': null,
    'declaration-block-single-line-max-declarations': null,
    'declaration-empty-line-before': null,
    'import-notation': null,
    'keyframes-name-pattern': null,
    'media-feature-range-notation': null,
    'no-descending-specificity': null,
    'property-no-deprecated': null,
    'rule-empty-line-before': null,
    'selector-class-pattern': null,
    'value-keyword-case': null,
    'order/properties-order': [
      propertyOrder,
      {
        unspecified: 'bottomAlphabetical',
      },
    ],
  },
};

export default stylelintConfig;
